config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 get 'bienvenida', to: 'home#index'
 root to: 'static_pages#home'
 
resources :articles

resources :phones
get '/states/:id/phones', to: 'states#phones', as: :state_phones

resources :semaphores 
get '/states/:id/semaphores', to: "states#semaphores", as: :state_semaphore
resources :states
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
has_rich_text :content
end

app/models/phone.rb
class Phone < ApplicationRecord
    belongs_to :state
    def self.get_latest_by_id
        all_phones = self.all.order(state: :asc)
         latest_phones = {}
    
        all_phones.each do |phone|
          # if(true)
          #   #do something
          # end
          # unless(false)
          #   # do something
          # end
          unless(latest_phones[phone.state_id])
            latest_phones[phone.state_id] = phone
          end
        end
    
        latest_phones
      end


end

app/models/semaphore.rb
class Semaphore < ApplicationRecord
    # Relaciones
    belongs_to :state
  
    # Enums
    enum color: [:verde, :amarillo, :naranja, :rojo]
  
    # Callbacks
    before_validation :set_end_date
  
    # validaciones 
    validates :color, inclusion: { in: %w(verde amarillo naranja rojo), message: "%{value} no está permitido" }
  
    

    def self.get_latest_by_states
      all_semaphores = self.all.order(fecha_ini: :desc)
      latest_semaphores = {}
  
      all_semaphores.each do |asem|
        # if(true)
        #   #do something
        # end
        # unless(false)
        #   # do something
        # end
        unless(latest_semaphores[asem.state_id])
          latest_semaphores[asem.state_id] = asem
        end
      end
  
      latest_semaphores
    end
  
    private
    def set_end_date
      (self.fecha_fin = self.fecha_ini + 2.weeks) if self.fecha_ini && !self.fecha_fin
    end
  end

app/models/state.rb
class State < ApplicationRecord
    has_many :phones
    has_many :semaphores
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         after_create :welcome_send
         def welcome_send
            UserMailer.welcome_send(self).deliver
         end
         

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, only: [:show, :edit,:update,:destroy]
    before_action :authenticate_user!, only: [:show, :create,:index,:new, :edit,:update,:destroy]

    def index
    @article = Article.order(created_at: :desc)
    end
    def show
    end
    def edit
    end

    def new
    @article = Article.new
    end
def update
    @article.update(title: params[:article][:title], content: params[:article][:content])
    redirect_to @article
end
def create
    @article = Article.create(title: params[:article][:title], content: params[:article][:content])
    redirect_to @article 
end
def destroy
    @article.destroy
    redirect_to root_path
end

def find_article
    @article = Article.find(params[:id])
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
    before_action :authenticate_user!
    # Ejecutar la función get_phone antes de las siguientes acciones:
     # - edit
     # - update
     # - show
     # - destroy
     before_action :get_phone, only: [:edit, :update, :show, :destroy]
    
    
    def index
        @phone = Phone.all
        @phones = Phone.get_latest_by_id
        
    end
    def new
        @phones = Phone.new(state_id: (params["estado"]))
        
    end
    def create
      @phone = Phone.create(phone_params, )
      redirect_to @phone
        Rails.logger.debug params.inspect
    end 
    def edit
    end
  
    def update
      @phones.update(phone_params)
      redirect_to root_url(estado: @phones.state_id)
    end
  
    def show
    end
    def destroy
        @phones.destroy
        redirect_to phones_path
      end

    private
  # Strong params
  def phone_params
    params.require(:phone).permit(:state_id, :numero)
  end

  def get_phone
    @phones = Phone.find(params[:id])
  end
  
end

app/controllers/semaphores_controller.rb
class SemaphoresController < ApplicationController
    before_action :datos, only: [:show, :edit, :update]
    def index
        @semaphore = Semaphore.all
        @semaphores = Semaphore.get_latest_by_states
    end
    def new
      @semaphore = Semaphore.new(state_id: (params["estado"]))
         
       
     #@semaphores = Semaphore.order(fecha_ini: :desc)
     #@semaphore = State.all
    end

    def create
        @semaphores = State.all
        @semaphore = Semaphore.create!(semaphore_params)
        redirect_to @semaphore
    end
    def show
    end
  
    def edit
    end
  
    def update
    end
    private
    def semaphore_params
        params.require(:semaphore).permit(:state_id,:color,:fecha_ini)
    end

    def datos
        @semaphore = Semaphore.find(params[:id])
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController


    def index
      @state = State.all
    end
    def semaphores
        @state = State.find(params[:id])
      end

      def phones
        @state = State.find(params[:id])
      end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:home]
    def home
        @states = State.all
        @semaphores = Semaphore.get_latest_by_states
        @phones = Phone.all
        #raise @semaphores.inspect
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/semaphores_helper.rb
module SemaphoresHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class ="card padding margin-top">
    <h3 class="text-uppercase"> <%= article.title %></h3> 
    <p class= "text-secondary"><%= article.created_at %> </p>
    <%= link_to "Ver más", article %>
    </div>

app/views/articles/_form.html.erb
<%= form_with(model: @article,local: true) do |form| %>

    <div class='field'>
     <%=form.label :title, "titulo" %>
     <%=form.text_field :title%>
     </div>
    <div class='field'>
     <%=form.label :content, "cuerpo de la noticia" %>
     <%=form.rich_text_area :content %>
     </div>

     <div>
     <%=form.submit "Guardar", class: "btn btn-primary mt-3"  %>
     </div>

   

     <%end%>

app/views/articles/edit.html.erb
<div class="small-container center-block">
<%= render "articles/form"%>

app/views/articles/index.html.erb
<div class="large-container center-block">
<%= render @article %> 
</div>

app/views/articles/new.html.erb
<div class="small-container center-block">
<%= render "articles/form"%>

app/views/articles/show.html.erb
<div class="small-container center-block">
<div class="container" id="states_container">
<h1><%=@article.title%> </h1>
<br>
</div>
<div class="container">
<%= @article.content%>
</div>
<div>
<br>
<%=link_to "Eliminar articulo",@article, class: "btn btn-primary", method: :delete%>
</div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
  <br>
  <%= render "layouts/partials/nav" %>
  <% if notice %>
  <p class="alert alert-primary"><%= notice %></p>
  <%end%>
  <%  if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <%end%>
  <%= yield %>
   

  </body>
</html>

app/views/layouts/partials/_nav.html.erb
<nav class="nav bg-light padding">
<li class="nav-item"> 
    <%= link_to "Inicio", root_path, class:"nav-link" %>
</li>
<li class="nav-item"> 
    <%= link_to "Crear Noticia",new_article_path, class:"nav-link" %>
</li>
<li class="nav-item"> 
    <%= link_to "Noticias",articles_path, class:"nav-link" %>
</li>



<% if user_signed_in? %>

<li class="nav-item"> 
<%= link_to "Cerrar sesión", destroy_user_session_path, method: "delete", class: "nav-link" %>
</li>
<% else %>
<li class="nav-item"> 
<%= link_to "Iniciar sesión", new_user_session_path,  class: "nav-link" %>
</li>
<% end %>


</nav>

app/views/phones/_form.html.erb
<%= form_with(model: phone, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :state_id, "Estado*"%>
      <%= form.select(:state_id, options_for_select(State.all.pluck(:estado, :id), 
      phone.state_id), {include_blank: true}, {class: "form-control", required: true}) %>
    </div>
  
    <div class="form-group">
      <%= form.label :number, "Número telefónico*" %>
      <%= form.text_field :numero, class: "form-control", required: true %>
    </div>
  
    <%= form.submit "Agregar Telefono", class: "btn btn-primary mt-3" %>
  <% end %>

app/views/phones/edit.html.erb
<div class="container">
<%= render 'form', phone: @phones %>
</div>

app/views/phones/index.html.erb
<div class="container ">
<div class="d-flex justify-content-around">
<h1>Teléfonos registrados</h1>
<%= link_to "Añadir registro", new_phone_path, class: "btn btn-secondary" %>
</div>
<div class="d-block card padding margin-top small-container center-block">
<% @phones.each do |id, phone| %>
  <div>
    <h3>Estado: <%= phone.state.estado %></h3>
    <p>Telefono: <%= phone.numero %></p>
    <%= link_to "Más información", state_phones_path(phone.state_id), class: "btn btn-primary" %>
    <%= link_to "Editar", edit_phone_path(phone), class: "btn btn-success" %>
    <%= link_to "Eliminar", phone, method: :delete, class: "btn btn-danger" %>
  </div>
  <hr>
  <hr>
<% end %>
</div>
</div>

app/views/phones/new.html.erb
<style>
      .hidden{
        display: none;
      }
    </style>
<div class="container">
<%= form_with(model: @phones, local: true) do |form| %>
<br>
    <div class="form_group">
   <h2> <%= form.label :state_id, "Estado: " %> <%= @phones.state.estado.capitalize %> </h2>
    <%=form.select(:state_id, options_for_select(State.all.pluck(:estado, :id), @phones.state_id), {include_blank: true}, {class: "form-control hidden", required: true}) %>
    </div>
    
    
    <div class= 'field'>
    <%=form.label :numero %>
    <%=form.text_field :numero %>
    </div>
    
    <div>
    <%= form.submit "Guardar",  class: "btn btn-primary mt-3" %>
    </div>
    <%end%>
    </div>

app/views/phones/show.html.erb
<div class="small-container center-block">

  <h3><p>Este es un teléfono que sirve para pedir ayuda</p></h3>
  <h4><p>Teléfono: <strong><%= @phones.numero %></strong></p></h4>

</div>

app/views/semaphores/_form.html.erb
<style>
      .hidden{
        display: none;
      }
    </style>
    <br> <br>
<%= form_with(model: semaphore, local: true) do |f| %>

    <div class="form-group">
     <h2> <%= f.label :state_id, "Estado: "%>      <%= @semaphore.state.estado.capitalize %> </h2>
      <% if params[:estado].present? %>
      <%= f.select :state_id, options_for_select(State.all.pluck(:estado, :id), semaphore.state_id), {include_blank: true}, {class: "form-control hidden", required: true}%>
      
      <% else %>
 
      <% end %>
     
    </div>
     
    <div class="form-group">
      <%= f.label :color, "Color del semáforo*" %>
      <%= f.select :color, options_for_select(Semaphore.colors.map{|s| [s.first.capitalize, s.first]}, semaphore.color), {include_blank: true}, {class: "form-control", required: true} %>
    </div>
    <div class="form-group">
      <%= f.label :start, "Fecha de inicio*" %>
      <%= f.date_field :fecha_ini, class: "form-control", required: true %>
    </div>
   
    <%= f.submit "Actualizar Color" ,class: "btn btn-primary mt-3"%>
  <% end %>

app/views/semaphores/index.html.erb
<div class="container ">
<div class="d-flex justify-content-around">
  <h1>Semaforo por estado</h1>  
  <%= link_to "Agregar registro", new_semaphore_path, class: "btn btn-primary align-self-center" %>
</div>
<div class="d-block card padding margin-top small-container center-block">

  <% @semaphores.each do |id, sem| %>
    <div class="w-100">
      <h3 class="text-uppercase">El estado <%= sem.state.estado.capitalize %> estuvo en semáforo <%= sem.color.titleize %></h3>
      <p class= "text-secondary">de <%= sem.fecha_ini %> al <%= sem.fecha_fin %></p>
      <%= link_to "Agregar Semaforo", new_semaphore_path(estado: sem.state_id) %>
      <%= link_to "Histórico del estado", state_semaphore_path(sem.state_id), class: "btn btn-secondary align-self-center" %>
</div>
    <hr>
    <hr> 
    
  <% end %>
</div>
</div>

app/views/semaphores/new.html.erb
<div class="container">
<div class="d-flex justify-content-around">

  <h1>Actualizando color de semáforo</h1>

</div>
<%= render 'form', semaphore: @semaphore %>
</div>

app/views/semaphores/show.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-around">
    <h1>Semáforo del estado de <%= @semaphore.state.estado.capitalize %></h1>
    <div class="d-flex">
    <%= link_to "ver semáforos", semaphores_path, class: "btn btn-primary align-self-center" %>
    <%= link_to "Histórico del estado", state_semaphore_path(@semaphore.state_id), class: "btn btn-secondary align-self-center" %>
    </div>
  </div>
  <ul>
    <li><strong>Color:</strong> <%= @semaphore.color.capitalize %></li>
    <li><strong>Fecha de inicio:</strong> <%= @semaphore.fecha_ini %></li>
    <li><strong>Fecha de finalización:</strong> <%= @semaphore.fecha_fin %></li>
  </ul>
</div>

app/views/static_pages/home.html.erb
<div class="small-container center-block">
<h1>Elige un Estado para Ver su Informacion</h1>
<div>
<%= select_tag :state_select, options_for_select(@states.map{ |s| [s.estado, s.id]}), 
{class: "form-control", required: true, include_blank: true}%>
  
  <!-- Clase para ocultar los divs -->
  <style>
      .hidden{
        display: none;
      }
    </style>

</div> 
<div class="col-9">
<div class="d-block card padding margin-top small-container center-block">
 <div class="small-container center">
<% if @states.present? %>
  <div id="states_container" >
    <% @states.each do |state| %>
  <div id="state_<%= state.id %>_box" class = "hidden">
        
        <h3><%= state.estado %></h3>
        <hr>
        <h5>Semáforo epidemiológico actual </h5>
      
        <% semaphore = @semaphores[state.id] %>
          
          <% if semaphore %>
          
            <div class = "w-100">
              <ul>
                <li><strong>Color:</strong> <%= semaphore.color.capitalize %></li>
                <li><strong>Fecha inicio:</strong> <%= semaphore.fecha_ini %></li>
                <li><strong>Fecha fin:</strong> <%= semaphore.fecha_fin %></li>
              </ul>
             </div>
             
          <% end %> 
          
          <%= link_to "Cambiar color ", new_semaphore_path(estado:state.id),
           class: "btn btn-secondary align-self-center"%>

              

            <!-- Colapse para Mostrar el Historico del estado-->
          <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Historico del estado
          </button>
          <!-- Contenido del Collapse-->
        <div class="collapse" id="collapseExample">
        <div class="card card-body">
          <% state.semaphores.each do |sem| %>
              <ul>
                <li><strong>Color:</strong> <%= sem.color.capitalize %></li>
                <li><strong>Fecha inicio:</strong> <%= sem.fecha_ini %></li>
                <li><strong>Fecha fin:</strong> <%= sem.fecha_fin %></li>
              </ul>
              <hr>
            <% end %>
        </div>
        </div>
                                

        <h5>Telefonos</h5>
        <ul>
        <% phones = @phones[state.id] %>
    <% state.phones.each do |phone| %>
        <li>Telèfono <%= phone.numero %></li>
          <%= link_to "Editar", edit_phone_path(phone), class: "btn btn-success" %>
        
        </ul>
        
        <% end %>
        <br><br>
        <%= link_to "Añadir Telèfono", new_phone_path(estado:state.id), class: "btn btn-secondary" %>
        </div>
       
    <% end %>
  </div>
  </div>
<% end %>
</div>
</div>
 <% if params[:state_id].present? %>

   <span data-state-selected>  <%= params[:state_id] %> </span>
 <% end %>
 </div>


<script>          
// Variable que almacena el estado actual seleccionado
// Añado el valor de 0 ya que es el div que se muestra
// en un inicio
let currentState = 0;
// Función que muestra el contenido a partir del cambio
// de valor del select
const handleChangeValue = ({target}) => 
{
  // Ocultar el div que se encuentra actualmente visible
  console.log(currentState)
  if(currentState)
  {
      const divToHide = document.querySelector('#state_'+currentState+'_box');
      !divToHide.classList.contains("hidden") && divToHide.classList.add("hidden");
  }
  // Actualiza el valor del estado a partir del valor seleccionado
  // La variable "target" corresponde al select que contiene los estados
  currentState = target.value;

  // Obtengo el div correspondiente al valor seleccionado
  
  const divToShow = document.querySelector('#state_'+currentState+'_box');

  // Muestro el div correspondiente eliminando la clase hidden 
  // (ver los estilos en la etiqueta head)
  divToShow.classList.contains("hidden") && divToShow.classList.remove("hidden");

  return;
};

// Añado la función al select una vez que el contenido de la página está lista
// para desplegarse.
window.addEventListener("DOMContentLoaded", () => {
  const stateSelect = document.querySelector('#state_select');
  stateSelect.onchange = handleChangeValue;
});

</script>
</div>
  